# 项目相关配置
yilifang:
  #名称
  name: YilifangFrameWork
  #版本
  version: 1.0.0
  #版权年份
  copyrightYear: 2018
  #头像上传路径
  profile: D:/profile/
  # 获取ip地址开关
  addressEnabled: true
#开发环境配置
server:
  context: 
       #网址
       url:  www.yilifang.com
       #手机网址
       wapUrl: wap.yilifang.com
       #手机网址名称
       wapName: yiliang yiliang
  #服务端口
  port: 8087
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 200
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 25
   
#日志配置
logging:
  #path: d:\\syncDatalogs 
  #path: /usr/local/software/communityservice
  level:
    com.cum3.yilifang: DEBUG
    org.springframework: INFO
    org.spring.springboot.dao: DEBUG
#用户配置
user:
  password:
    #密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5
  # 首页地址
  indexUrl: /index
#断点续传配置
breakpoint:
  upload:
    #上传附件临时上传目录
    dir: D:/uploads/
    #1024*1024=1 048 576,50M=50 242 880
    chunkSize: 50 242 880
ocr:
   appId: 14372647
   apiKey: YF5gYETQyYnW77a3cbtuk4lx
   secretKey: iO2tslN1OlXtHet3Q5pLVKjXauneNVW4 
oss:
  #选择云服务器类型 ：1七牛云 2阿里云 3腾讯云 4ftp 这里使用ftp附件服务器
  type: 4
  #七牛云相关配置
  qiniuAccessKey: Pxh4u_G_OiM3Tn8WTX2Vef8kXbyQfZYP9Ww5P_Af
  qiniuBucketName: yilifang
  qiniuDomain: http://pfa3t91df.bkt.clouddn.com
  qiniuPrefix: upload
  qiniuSecretKey: sX54pyzDF2HER-xDygh9il6TgqgrSSDRMM6PdbgW
  #阿里云相关配置
  aliyunAccessKeyId: 
  aliyunAccessKeySecret: 
  aliyunBucketName:
  aliyunDomain: 
  aliyunEndPoint: 
  aliyunPrefix: 
  #腾讯云相关配置
  qcloudAppId: 1257775707
  qcloudBucketName: 
  qcloudDomain: https://yilifnag-1257775707.cos.ap-guangzhou.myqcloud.com
  qcloudPrefix: upload
  qcloudSecretId: AKIDZ5Tgv2rgDZjhT4Bo13CD2g8QWQEHdzZx
  qcloudSecretKey: MZeZZUEm9KJBvUUXZR7f3HWEpFUXSBj5
  qcloudRegion: ap-guangzhou
  #ftp附件服务器
  ftpHost: 132.232.33.242
  ftpPort: 21
  ftpUsername: ftpusertwo
  ftpPassword: 123456123456
  initialSize: 0
  encoding: UTF-8
  ftpRootPath: /var/myftp/upload/                #存放附件服务器根目录
  ftpDomain: https://filemutiupload.one-cm3.com  #文件夹映射域名
  ftpMinPort: 60021                              #主动模式ftpclient端口范围
  ftpMaxPort: 61021
#Spring配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  #文件上传
  servlet:
     multipart:
       max-file-size:  2048MB
       max-request-size:  60MB
  #使用redis做缓存
  redis:
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      jedis:
        pool:
          #连接池最大连接数（使用负值表示没有限制）
          max-active: 100
          # 连接池中的最小空闲连接
          max-idle: 10
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: 100000
      # 连接超时时间（毫秒）
      timeout: 60000
      #默认是索引为0的数据库
      database: 0
  messages:
    #国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      #格式化输出 
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化（总是返回）
    defaultPropertyInclusion: ALWAYS
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true
  profiles: 
    active: druid
  #devtools
  devtools:
    restart:
      #热部署开关
      enabled: true
  flyway:
    url: 
#MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.cum3.yilifang.project
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:com/cum3/yilifang/project.*.*.mapper
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - com.cum3.yilifang.framework.web.mapper.BaseMapper
  notEmpty: true
# PageHelper
pagehelper: 
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql 
# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /favicon.ico,/images/*,/js/*,/css/*
  # 匹配链接
  urlPatterns: /*
#微信小程序配置
smallrouting:
          appId: wx64cd9d5818e5a8ee
          Secret: 442f53e164af6464a0827649e5f1c103
# 支付配置
wx:
  pay:
    #微信公众号或者小程序等的appid 必填 是
    appId: wx64cd9d5818e5a8ee 
    #微信支付商户号   必填 是
    mchId: 1520340771
    #微信支付商户密钥  必填 是
    mchKey: JDI1h231si287eIJi28difujfJDKWI24
    #服务商模式下的子商户公众账号ID 必填 否
    subAppId: 
    #服务商模式下的子商户号  必填 否
    subMchId: 
    #p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头） 必填 是
    keyPath: classpath:apiclient_cert.p12
    #支付成功通知的回调地址
    notifyUrl: https://221555h62w.imwork.net/pay/notify/order